name: 'add-reviewers-action'
description: GitHub Action to add reviewer(s) to a pull request.'
branding:
  icon: 'user-plus'
  color: 'gray-dark'
author: 'sakhnovict'
inputs:
  reviewers:
    description: 'Reviewer(s) to add, in comma separated list.'
    required: true
  token:
    description: GitHub Personal Access Token
  remove:
    description: 'Remove a review request (defaults to false)'
runs:
  using: 'node16'
  main: 'dist/index.js'
